"""Maintain inspected-media metadata; does not copy reference media into production."""
import json,hashlib
from pathlib import Path
root=Path('artifacts/references')
fetch=json.loads((root/'fetch-index.json').read_text())
rows=[]
def add(id,file,url,credit,observed,by='content and art agents',context='Still image; no video timecode'):
 p=root/file
 rows.append(dict(sourceId=id,localReference=str(p),url=url,accessedOn='2026-09-10',inspected=True,inspectedBy=by,sha256=hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else None,credit=credit,distribution='reference_only',context=context,observed=observed))
keys={'green-turtle':'green-turtle-noaa','casey':'casey-aap','adelie-penguin':'adelie-aap','emperor-penguin':'emperor-aap','weddell-seal':'weddell-aap','southern-elephant-seal':'elephant-aap','leopard-seal':'leopard-aap','snow-petrel':'snow-petrel-aap','bloody-belly-comb-jelly':'mbari-bloody-belly-comb-jelly','barreleye':'mbari-barreleye-fish','vampire-squid':'mbari-vampire-squid','big-red-jelly':'mbari-big-red-jelly','redhead-larvacean':'mbari-redhead-larvacean'}
observed={'green-turtle':'Oval shell, scutes, long foreflippers, smaller rear flippers; olive-brown upper body.','casey':'Rocky coastal margins and pale ice under blue sky; local coastal composition.','adelie-penguin':'Black head, white eye ring, white belly and short flippers.','emperor-penguin':'Tall adults in ice landscape; black/white body and yellow neck patches.','weddell-seal':'Robust gray seal, rounded head, mottled coat and short muzzle.','southern-elephant-seal':'Rounded brown-gray body and paired hind flippers; female reconstruction omits male proboscis.','leopard-seal':'Long neck/head and body, spotted pale belly and long foreflippers.','snow-petrel':'White body and pointed wings with black eyes and small black bill.','bloody-belly-comb-jelly':'Red lobate body, two large oral lobes, eight reflective comb rows.','barreleye':'Transparent head shield over green tubular eyes; dark face spots are nares.','vampire-squid':'Red mantle, paired fins and web-connected arms.','big-red-jelly':'Thick red bell and short broad oral arms; no thin trailing tentacles.','redhead-larvacean':'Translucent mucus house enclosing red-centered small body and long tail.'}
for k,id in keys.items():
 url=fetch[k]['og'][0]
 isdeep=k in ['bloody-belly-comb-jelly','barreleye','vampire-squid','big-red-jelly','redhead-larvacean']
 context='MBARI ROV research-light photograph. Dive identifier retained in original filename where supplied; image-specific depth not stated in this species-page caption. Species depth range is separately cited; do not infer a precise dive depth.' if isdeep else 'Still image; no video timecode'
 add(id,k+'.jpg',url,'MBARI © (reference only)' if isdeep else ('NOAA Fisheries; consult item caption for third-party credit' if k=='green-turtle' else 'Australian Antarctic Program; item photographer credits retained on source page'),observed[k],context=context)
add('buck-front','buck-front.png','https://www.nps.gov/buis/planyourvisit/upload/Buck-Island-Front.pdf','NPS brochure, 2011; mixed third-party photographic/illustration credits; reference only','Entire front page inspected at 2000px: labelled elkhorn broad branches, Atlantic blue tang, hawksbill, lacy fan, spiny lobster, brown pelican and pale sandy paths.',context='PDF front/page 1, rasterized using pdftoppm; no video timecode')
add('clam-dbca','giant-clam.jpg','https://www.dbca.wa.gov.au/sites/default/files/styles/feature_large_850x425/public/2023-05/giant_clam_adobe.jpeg?itok=PuVl5VtA','DBCA / Adobe stock; no redistribution','Deep radial shell folds and exposed blue mantle.','art agent')
add('natgeo-clam','natgeo-clam.jpg','https://i.natgeofe.com/n/f6b59937-b36f-4778-8486-793ce484b88d/giant-clam.jpg?w=750','DeAgostini / Getty Images via National Geographic; no redistribution','Heavy pale two-part shell, dark patterned wavy mantle and siphon openings.','content agent')
add('anemonefish-dbca','anemonefish.jpg','https://www.dbca.wa.gov.au/sites/default/files/styles/feature_large_850x425/public/2023-05/anemonefish_adobe_plie.jpeg?itok=s2s8MuOV','PlieDo / Adobe via DBCA; no redistribution','Orange oval fish with white bands edged dark, rounded tail beside anemone.','art agent')
add('acropora-museum','acropora-museum.jpg','https://media.australian.museum/media/dd/images/DSC09016.b20e858.width-1600.2bcb015.jpg','© Australian Museum; no redistribution','Branching Acropora at Lizard Island, pale axial tips and radial corallites; spawning particles are omitted from model.',context='Caption identifies Acropora spawning at Lizard Island; morphology only, Green Island occurrence supplied separately')
add('green-rail','buff-banded-rail.jpg','https://visitgreenisland.com.au/files/2021/03/buff-banded-rail-1260x700.jpg','Visit Green Island; no redistribution','Brown back, white eyebrow, chestnut cheek, barred black/white underside with buff breast band.','art agent')
add('halodule-visual','halodule-illustration.png','https://ian.umces.edu/site/assets/files/17644/halodule-uninervis.svg','Catherine Collier / JCU, UMCES; CC BY-SA4.0, reference only','Narrow flat leaves rise from rhizome shoots, three-toothed tips and roots; illustrated botanical morphology.')
add('halodule-photo','halodule-photo.jpg','https://upload.wikimedia.org/wikipedia/commons/9/96/Seagrass_Halodule_uninervis_%285777808662%29.jpg','Paul Asman and Jill Lenoble, CC BY2.0; reference only','Thin ribbon leaves form meadow; Wakaya Fiji 2011 image used only for morphology.')
add('turtle-grass-source','turtle-grass.jpg','https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/51/2017/04/seagrass-type-turtlegrass.jpg','Cathleen Bester / Florida Museum; no redistribution','Broad, long strap leaves distinct from Halodule narrow leaves.','art agent')
add('grunt-museum','blue-striped-grunt.jpg','https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/66/2017/05/Haemulon-sciurus-01.jpg','© Doug Perrine / Florida Museum; no redistribution','Yellow deep oval body with many thin curved blue stripes and dark forked tail.')
add('benwood-grunts','benwood-grunts.jpg','https://upload.wikimedia.org/wikipedia/commons/8/85/Grunts_Benwood_20080309.jpg','Jstuby, CC0; reference only','School beside rough wreck surface. Photographer labels bluestriped grunts and schoolmasters; grunt stripes corroborated against museum image.','content agent',context='Benwood, 9 March 2008, 08:43:49; historical occurrence')
add('keys-creatures','yellowtail-snapper.jpg','https://floridakeys.noaa.gov/media/img/20240201-yellow-tail-snapper-1000.jpg','NOAA Florida Keys; exact page credit retained; reference only','Silver streamlined body, gold lateral stripe into deep forked yellow tail.','art agent')
add('keys-creatures','green-moray.jpg','https://floridakeys.noaa.gov/media/img/20240201-green-moray-eel-rachelplunkett-1000.jpg','Rachel Plunkett / NOAA; reference only','Long olive-green eel, blunt head, small eye and continuous dorsal edge; no pectoral fins.','art agent')
add('sergeant-major-museum','sergeant-major.jpg','https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/66/2017/05/Abudefduf-saxatilis-01.jpg','© George Ryschkewitsch / Florida Museum; no redistribution','Five dark body bars, yellow upper back, silver disk-like fish.','art agent')
add('krill-aap','antarctic-krill.jpg','https://www.antarctica.gov.au/site/assets/files/45495/2174c6.1200x630.jpg','Australian Antarctic Program; item photographer credit retained; reference only','Shrimp-like translucent body, black eyes, red gut and segmented tail.','art agent')
for file,slug,obs in [('benwood-bow.jpg','20240126-benwood-bow-1000.jpg','Raised broken bow, encrusted steel and open exterior.'),('benwood-crushed-bow.jpg','20240126-benwood-crushed-bow-1000.jpg','Collapsed metal and open floor structure, no intact upper ship.'),('benwood-orthomosaic.jpg','20240124-benwood-bow-orthomosaic-model-1000.jpg','2017 survey top view establishes footprint, broken bow and triangular supports.')]:
 add('benwood-noaa',file,'https://floridakeys.noaa.gov/media/img/'+slug,'NOAA Florida Keys; exact page credits retained; reference only',obs,'art agent',context='2017 survey orthomosaic / present-remains photographs on NOAA page, accessed 2026-09-10; not a reconstruction of the intact vessel')
unavailable=[dict(id='bbc-clownfish',url='https://www.bbcearth.com/incredible-teamwork-from-little-clownfish',title='Incredible Teamwork From Little Clownfish',publisher='BBC Earth / Blue Planet II',pageInspected=True,footageInspected=False,timecode=None,status='Specific clip page found, but playable footage unavailable to inspect in this environment. Listed duration 2 minutes is not a watched interval. No motion or fact claim relies on it.',rights='BBC copyright, reference_only; no downloading or redistribution'),dict(id='aims-coral-photo',url='https://www.aims.gov.au/sites/default/files/2022-08/different_coral_shapes_706px.jpg',pageInspected=True,footageInspected=False,timecode=None,status='AIMS article text inspected; image repeatedly timed out/HTTP2 failure. Replaced with inspected Australian Museum Acropora photo.',rights='reference_only'),dict(id='benwood-panorama',url='https://sanctuaries.noaa.gov/vr/florida-keys/benwood-wreck/',pageInspected=True,footageInspected=False,timecode=None,status='Introductory text inspected; interactive panorama not inspected. Separate NOAA photographs and orthomosaic inspected instead.',rights='reference_only')]
Path('content/evidence/reference-index.json').write_text(json.dumps({'accessedOn':'2026-09-10','media':rows,'unavailable':unavailable},indent=2)+'\n')
s='# Inspected reference index\n\nMedia access on 2026-09-10. This index records images actually opened with image inspection tools, including inspection delegated to the art worker. Download success alone is not treated as inspection. References stay in ignored `artifacts/references/`; none are production assets. Local SHA-256 hashes and machine-readable access outcomes are in [reference-index.json](../content/evidence/reference-index.json). Shipping rights for original models/audio belong in the separate asset registry. Copyrighted references are not licensed for copying into the game.\n\n## Photographic and illustrated references\n\n| Source ID / exact item | Inspection / context | Observed features | Credit / rights |\n|---|---|---|---|\n'
for r in rows:s+=f"| `{r['sourceId']}` — [exact image]({r['url']}); `{r['localReference']}` | {r['inspectedBy']}; {r['context']} | {r['observed']} | {r['credit']}; reference only |\n"
s+='\n## Documentary and unavailable media\n\nNational Geographic: [Giant clam article](https://www.nationalgeographic.com/animals/invertebrates/facts/giant-clam) and its DeAgostini/Getty photograph were inspected. This is a still-photo reference, so no video timestamp applies. BBC: a specific official clip was located, but no footage was successfully watched. Neither publisher supplies game assets.\n\n'
for u in unavailable:s+=f"- [{u.get('title',u['id'])}]({u['url']}): {u['status']} Rights: {u['rights']}.\n"
s+='\n## Deep imagery context\n\nMBARI filenames preserve supplied ROV identifiers: comb jelly D1136, vampire squid T0682, big red jelly D1043 and larvacean T1112. The selected species-page images did not provide individual measured depths alongside each caption; no depth has been invented for those frames. Species accounts supply supported depth intervals. The [MBARI 2024 report](https://annualreport.mbari.org/2024/story/bringing-the-deep-sea-to-land-one-ride-at-a-time) separately captions a bloody-belly comb jelly in Monterey Bay at 493 m (2019 photograph); the HTML caption was inspected. D/T identifiers are recorded as supplied, without guessing an ROV name or timestamp. Illumination is research light. No full video archive is claimed to have been watched.\n\n## Access/reproducibility notes\n\nSome Python urllib requests returned HTTP 403; ordinary curl requests with a browser User-Agent successfully retrieved the exact public images and the images were then opened. No login, paywall or access control was bypassed. The NOAA hosted 2022 Buck Island report download was unavailable, but the same NPS report was obtained from the NPSHistory mirror and its species/locality passages inspected with `pdftotext` (printed pp.23–24 and 120, DOI 10.36967/nrr-2293288). Facts are independently sourced from exact agency/species pages in the catalog. `fetch_references.py` preserves initial retrieval outcomes; later successful inspection is recorded here, not inferred from the fetch log.\n'
s+='\n## Additional locality audit\n\nThe [taxon-strength audit](../content/evidence/taxon-strength-audit.json) records the inspected Australian Museum Tridacna revision, including PDF hash and rendered pages 9 and 12 (printed p.170 and plate XXVII caption). This is historical specimen/locality evidence, not a new photographic model reference. The scanned text explicitly names Green Island off Cairns and Tridacna gigas. An inaccessible Queensland park-plan PDF and unrelated Green Island localities were excluded.\n'
Path('docs/REFERENCE_INDEX.md').write_text(s)
print(len(rows),'inspected media records')
